### ISSUE TITLE
eval_sisr command showing error.

### ISSUE THREAD

**Issue by Saddy21** [um-dsrg/RUMpy#3]
Hi
I was trying to use **eval_sisr**  command but it is showing 
![error1](https://github.com/um-dsrg/RUMpy/assets/98169680/8fa11556-a230-443f-a05b-384212442b70)

" **### AttributeError: 'SISRInterface' object has no attribute 'name'** "
This is my config file 
![error2](https://github.com/um-dsrg/RUMpy/assets/98169680/b7e4f083-848b-4c18-be2d-26d1d107ae1c)

Kindly help.

**Comment by mattaq31** [comment]
Hi, that error indicates that the code didn't find the metadata (i.e. description to properly initialise hyperparameters) for the model you're loading.  Can you please indicate if you retained the config.toml file in the rcan_batch_4_complex folder?

**Comment by mattaq31** [comment]
Another possibility - can you confirm if you properly set the filepaths in 'model_loc' and the hr/lr directories?  Try use absolute filepaths to make sure you're definitely in the right place.

**Comment by Saddy21** [comment]
> Hi, that error indicates that the code didn't find the metadata (i.e. description to properly initialise hyperparameters) for the model you're loading. Can you please indicate if you retained the config.toml file in the rcan_batch_4_complex folder?



> Hi, that error indicates that the code didn't find the metadata (i.e. description to properly initialise hyperparameters) for the model you're loading. Can you please indicate if you retained the config.toml file in the rcan_batch_4_complex folder?

Hi
This is the config.toml in rcan_complex folder 
![s1](https://github.com/um-dsrg/RUMpy/assets/98169680/cfa1f81a-1d30-41a3-831e-a2b69945447c)

**Comment by mattaq31** [comment]
Ah now I see the issue - model_loc should be the path to the parent folder where rcan_batch_4 is saved.  I.e. if you have:

```/Users/test/downloads/rcan_batch_4```

then model_loc should be set to:

```/Users/test/downloads/```

This setup allows you to place multiple models in the folder and the code will be able to find them all.  Alternatively, you can just do the full absolute file path in model_and_epoch:

```toml
model_and_epoch = [['/Users/test/downloads/rcan_batch_4','best']]
```

**Comment by mattaq31** [comment]
In the first config file you sent you would just need to do:

```toml
model_loc = './Results'
```

**Comment by Saddy21** [comment]
> In the first config file you sent you would just need to do:
> 
> ```toml
> model_loc = './Results'
> ```

Thanks it is working now.
