### ISSUE TITLE
Model training

### ISSUE THREAD

**Issue by zoelee70** [um-dsrg/RUMpy#8]
I am trying to install and run DeepFIR on a MAC.  I am confused on how exactly to train the models and load them into the Results folder.  Are there pre-trained models available for use?

**Comment by KeithGeorgeCiantar** [comment]
Hello, thank you for using our repository!

If you would like to use the GUI, I had a discussion to address certain issues in the comments of the instruction video on YouTube. You go through the comments [here](https://www.youtube.com/watch?v=sptjtztnQnE&ab_channel=KeithGeorgeCiantar). Make sure to click 'Read More' on some of the comments because they're pretty long. They also contain some general information that might be helpful.

You can get the pre-trained models from the README [here](https://github.com/um-dsrg/RUMpy#pre-trained-model-weights), the first link is for the models in the first paper, the second link is for models from our latest paper.

For tips to run the models in eval/inference mode, you should check out issue #3.

For tips regarding issues you might run into when training, kindly check out issue #4.

Hope this helps!

**Comment by zoelee70** [comment]
Thank you the comments on the video explained a lot.  I was able to download the pre-trained models and edited the models.csv file to:
name,label,location,epoch,group
qrcan_ma_dan_blind_complex,"RCAN with DAN",/Users/zl/RUMpy-main/models/complex_pipeline_models,best,”Complex Data"

I was able to create the DeepFIR_GUI.app but am getting an error on the API connection and the models are not loading.  I believe the problem has to do with my file structure.  Should the RUMpy_main folder reside inside the virtual environment?  Also I am unable to locate the .\resources\app folder in the downloaded code.

Thank you

**Comment by KeithGeorgeCiantar** [comment]
Good to hear you're making progress! I'll try to address your issues one by one to make sure everything is covered.

-----

To start, the main use of the GUI is a demo application to quickly run the models on videos and images. The GUI can either be run by cloning the repository and then following the instructions [here](https://github.com/um-dsrg/RUMpy/tree/main/GUI#deep-fir-gui), or by downloading the packaged version from [here](https://github.com/um-dsrg/RUMpy/releases/tag/v0.1.0-alpha).

If I have understood correctly, since you're using macOS, you have downloaded the file `DeepFIR_GUI-darwin-x64.zip` and have managed to run the application. For the `.\resources\app`, you should be able to find it in `.\DeepFIR_GUI-darwin-x64\DeepFIR_GUI.app\Contents\Resources\app`, or `.\DeepFIR_GUI.app\Contents\Resources\app`. It is only created when the GUI is packaged, so it is not found in the code itself.

It is important to note that the GUI is only the frontend, so to be able to load and run a model, the backend API would also need to be running. I will explain how to run the API in the next section.

-----

Moving on to the API, this is the brains of the GUI application. The API backend for the GUI is run via the script `RUMpy\GUI\deep_fir_server.py`. This script uses the code in the repository to load and run the models. To run the script you need to follow these steps:
1. Clone the RUMpy repository.
2. Install Anaconda/Miniconda.
3. Open the terminal.
4. Follow the steps from [here](https://github.com/um-dsrg/RUMpy/tree/main#installation) to setup the Python environment. *Note: the Python environment does not need to be manually edited and should be managed through conda. The files in the environment and files in RUMpy_main are NOT dependent on each other and should be kept in separate locations.*
5. On the same environment, follow the steps from [here](https://github.com/um-dsrg/RUMpy/tree/main/GUI#backend-super-resolution-system---flask) to install the remaining packages for the API.
6. In the terminal, navigate to the `RUMpy_main\GUI` folder.
7. Activate the environment, and run the command `python deep_fir_server.py` or `python3 deep_fir_server.py`. This might take a few seconds until the local server finishes setting up.
8. You should now have a local server running on your machine, take note of the output on the terminal to check the server's address.

Now that you have the backend API running, keep it running and open the DeepFIR_GUI.app. From here you can go to the Settings page and press the `Test API Connection` button to see if the GUI app can communicate with the backend server. If there is an error, make sure that the `DeepFIR API URL` has the same value as the output from the terminal (in general it should be http://127.0.0.1:5000/). If everything is working as expected, you now have all the components ready to be used.

-----

With everything set up, you should now be able to perform inference using the GUI. With all the pre-requisites from the previous two sections taken care of, the process to load and run the models should be as follows:
1. Open the terminal.
2. Activate the Python environment.
3. In the terminal, navigate to the `RUMpy_main\GUI` folder.
4. Run the command `python deep_fir_server.py` or `python3 deep_fir_server.py`.
5. In the file explorer, go the folder `.\DeepFIR_GUI.app\Contents\Resources\app` and check that the `models.csv` looks like what you've written in your previous comment.
6. Open the DeepFIR_GUI.app.
7. Go to the Settings page in the app.
8. Click the `Test API Connection` to make sure that the backend is working.
9. In the dropdown for `Super-Resolution Model`, you should be able to find `RCAN with DAN` and select it.
10. If you have a GPU, you can leave the `Processor` dropdown as is, otherwise you can switch to CPU.
11. Go to the Super-Resolution page, now you should be able to load an image or a video and use the app normally. *Note: using the CPU will have a longer computation time to see the super resolved output.*

-----

Hope this helps!

**Comment by zoelee70** [comment]
Thank you for taking the time to help me out.   I have been able to create the DeepFIR_GUI.app and the models.csv was correctly installed.  

I am having trouble when I run the python3 deep_fir_server.py command.  I am getting a number of errors.  Do you have any suggestions?  Thank you
<img width="1159" alt="Screenshot 2023-11-30 at 11 20 17 AM" src="https://github.com/um-dsrg/RUMpy/assets/145230120/4a246c62-4ce5-46e2-a705-e8ce827d0524">

**Comment by KeithGeorgeCiantar** [comment]
Great to hear you've almost managed to get everything working!

According to the screenshot you sent, you were attempting to run `python3 deep_fir_backend_script.py`. At the moment, that script is not used when running the API backend, but it was something that we were testing and didn't fully finalise. You can get further details on it [here](https://github.com/um-dsrg/RUMpy/tree/main/GUI#ideas-for-further-development).

For the API backend, you need to run `python3 deep_fir_server.py` or `python deep_fir_server.py`. This should give you the functionality you need to be able to load and run models.

Hope this helps!

**Comment by zoelee70** [comment]
I get a bus error with the python3 deep_fir_server.py command

zsh: bus error  python3 deep_fir_server.py

**Comment by zoelee70** [comment]
<img width="347" alt="Screenshot 2023-12-01 at 2 35 17 PM" src="https://github.com/um-dsrg/RUMpy/assets/145230120/75230824-e245-4314-ad7d-95364801ac80">

I have no idea how to solve this error do you have any suggestions.  Thank you

**Comment by KeithGeorgeCiantar** [comment]
Sorry to hear about this issue! This is a new one to me, but I might have some ideas to try.

1. Check that you're using the correct Python environment. If you installed everything on base, use `conda list` and `pip list` to ensure all the required packages are installed. Otherwise, you need to activate the environment. The main package lists can be found [here](https://github.com/um-dsrg/RUMpy/blob/main/requirements.txt) and [here](https://github.com/um-dsrg/RUMpy/blob/main/pip_requirements.txt), and the [Flask](https://flask.palletsprojects.com/en/2.3.x/) package is also required.
2. Try commenting out all the code expect for the imports and re-try running the script. This should narrow it down to see whether the issue is with the packages or the code.
3. Try creating a conda environment with an older version of Python. During our development, with mainly worked with Python 3.7 and 3.8, so to create the environment we would use the command `conda create -n *environment_name* python=3.7`. I strongly suggest creating a separate environment instead of re-installing everything on `base`.
4. Check if certain packages/dependencies have issues with the Mac products. The custom Apple chips might need special attention when installing packages.

Let me know if any of these help!

**Comment by zoelee70** [comment]
I am making progress.  I installed python 3.7 in a conda environment and the bus error disappeared.  When I would run: python deep_fir_server.py  I was getting a module not found error on the deep_fir_server.py line 12 (from rumpy.SISR.models.interface import SISRInterface)  I added two lines to  deep_fir_server.py before line 12: 
import sys
sys.path.append('../')

Now when I run python deep_fir_server.py I do not get any errors and I can run along with the front end app.  However, the models are not being installed.  The models.csv is in the resources folder and has been updated. Any suggestions?

Thank you

**Comment by KeithGeorgeCiantar** [comment]
Ok great, we're almost there!

I think I know why you were getting an error at line 12. In the installation instructions [here](https://github.com/um-dsrg/RUMpy#local-installation), point 4 says to do `pip install -e .`, which is a command that installs the rumpy code as a package. 

When you have the terminal open, navigate to the RUMpy_main directory, activate the conda environment, and run the command `pip install -e .`. This should install the rumpy code as a package in the environment. Then when you run the command `python deep_fir_server.py`, the script should be able to use the rumpy code as a package without any issues. I'm not sure whether you need the `sys.path.append('../')`, but it may be an OS-related thing.

Hopefully this should be the last thing that's required!

**Comment by zoelee70** [comment]
I am able to see the models in the DeepFIR_GUI and am able to open the API URL:
<img width="1011" alt="Screenshot 2023-12-04 at 5 17 32 PM" src="https://github.com/um-dsrg/RUMpy/assets/145230120/eb59a862-1b9d-4de1-9d61-e53535619c84">

when I try to load a model I get the following error message:

<img width="1918" alt="Screenshot 2023-12-04 at 5 15 55 PM" src="https://github.com/um-dsrg/RUMpy/assets/145230120/abcdc0c9-974b-4898-b470-e986e043a866">

my models.csv file is:

<img width="1177" alt="Screenshot 2023-12-04 at 5 16 38 PM" src="https://github.com/um-dsrg/RUMpy/assets/145230120/fe177478-b567-41fb-bcef-a5453539dcca">

Do you think there is a path issue similar to the error I was getting in the deep_fir_server.py module above?

Thank you for your help - as you can most likely guess I am not a programmer

**Comment by KeithGeorgeCiantar** [comment]
Could you try setting the processor to `CPU` and then pressing `Load Model`?

**Comment by zoelee70** [comment]
I tried two models selecting the CPU and got errors with both.
<img width="1194" alt="Screenshot 2023-12-04 at 7 38 22 PM" src="https://github.com/um-dsrg/RUMpy/assets/145230120/0be58b32-992a-4be5-ba07-686f1eec528d">

**Comment by KeithGeorgeCiantar** [comment]
Ok it seems that there's an issue with the version of `einops`. Could you do `conda list` or `pip list`, and tell me the version you have installed? According to an issue I found [here](https://github.com/facebookresearch/esm/issues/637), it might be there was an update that caused issues.

**Comment by zoelee70** [comment]
(base) zl@iMac-Pro ~ % cd a_project
(base) zl@iMac-Pro a_project % conda activate my_env
(my_env) zl@iMac-Pro a_project % conda list
# packages in environment at /Users/zl/miniconda3/envs/my_env:
#
# Name                    Version                   Build  Channel
anyio                     3.7.1              pyhd8ed1ab_0    conda-forge
aom                       3.5.0                hf0c8a7f_0    conda-forge
appnope                   0.1.3              pyhd8ed1ab_0    conda-forge
argon2-cffi               23.1.0             pyhd8ed1ab_0    conda-forge
argon2-cffi-bindings      21.2.0           py37h69ee0a8_2    conda-forge
attrs                     23.1.0             pyh71513ae_1    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                pyhd8ed1ab_3    conda-forge
backports.functools_lru_cache 1.6.5              pyhd8ed1ab_0    conda-forge
beautifulsoup4            4.12.2             pyha770c72_0    conda-forge
blas                      2.120                       mkl    conda-forge
blas-devel                3.9.0              20_osx64_mkl    conda-forge
bleach                    6.1.0              pyhd8ed1ab_0    conda-forge
blosc                     1.21.5               heccf04b_0    conda-forge
bottleneck                1.3.5            py37h4de8ad1_0    conda-forge
brotli                    1.0.9                hb7f2c08_9    conda-forge
brotli-bin                1.0.9                hb7f2c08_9    conda-forge
brotli-python             1.0.9            py37h0582d14_7    conda-forge
brunsli                   0.1                  h046ec9c_0    conda-forge
bzip2                     1.0.8                h10d778d_5    conda-forge
c-ares                    1.23.0               h10d778d_0    conda-forge
c-blosc2                  2.11.3               h354e526_0    conda-forge
ca-certificates           2023.11.17           h8857fd0_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cairo                     1.16.0            h904041c_1014    conda-forge
certifi                   2023.11.17         pyhd8ed1ab_0    conda-forge
cffi                      1.15.1           py37h7346b73_1    conda-forge
cfitsio                   4.0.0                hb20e66c_0    conda-forge
charls                    2.3.4                he49afe7_0    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
click                     8.1.3            py37hf985489_0    conda-forge
click-config-file         0.6.0              pyhd8ed1ab_1    conda-forge
cloudpickle               2.2.1              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6              pyhd8ed1ab_0    conda-forge
comm                      0.1.4              pyhd8ed1ab_0    conda-forge
configobj                 5.0.8              pyhd8ed1ab_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
cytoolz                   0.12.0           py37h994c40b_0    conda-forge
dask-core                 2022.2.0           pyhd8ed1ab_0    conda-forge
debugpy                   1.6.3            py37hf6dfe07_0    conda-forge
decorator                 5.1.1              pyhd8ed1ab_0    conda-forge
deepdiff                  6.7.1              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
einops                    0.7.0              pyhd8ed1ab_0    conda-forge
entrypoints               0.4                pyhd8ed1ab_0    conda-forge
exceptiongroup            1.2.0              pyhd8ed1ab_0    conda-forge
expat                     2.5.0                hf0c8a7f_1    conda-forge
ffmpeg                    5.1.2           gpl_h8b4fe81_106    conda-forge
filelock                  3.13.1             pyhd8ed1ab_0    conda-forge
flask                     2.2.2            py37hecd8cb5_0  
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 h77eed37_1    conda-forge
fontconfig                2.14.2               h5bb23bf_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.38.0           py37h8052db5_0    conda-forge
freetype                  2.12.1               h60636b9_2    conda-forge
fsspec                    2023.1.0           pyhd8ed1ab_0    conda-forge
gettext                   0.21.1               h8a4c099_0    conda-forge
giflib                    5.2.1                hb7f2c08_3    conda-forge
gmp                       6.3.0                h93d8f39_0    conda-forge
gnutls                    3.7.9                h1951705_0    conda-forge
graphite2                 1.3.13            h2e338ed_1001    conda-forge
h5py                      3.7.0           nompi_py37hdc5a9f1_101    conda-forge
harfbuzz                  5.3.0                h08f8713_0    conda-forge
hdf5                      1.12.2          nompi_h48135f9_101    conda-forge
huggingface_hub           0.16.4             pyhd8ed1ab_0    conda-forge
icu                       70.1                 h96cf925_0    conda-forge
idna                      3.6                pyhd8ed1ab_0    conda-forge
imagecodecs               2021.11.20       py37h04bde26_2    conda-forge
imageio                   2.31.5             pyh8c1a49c_0    conda-forge
imageio-ffmpeg            0.4.9              pyhd8ed1ab_0    conda-forge
importlib-metadata        4.11.4           py37hf985489_0    conda-forge
importlib_resources       6.0.0              pyhd8ed1ab_0    conda-forge
ipykernel                 6.16.2             pyh736e0ef_0    conda-forge
ipython                   7.33.0           py37hf985489_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                8.1.1              pyhd8ed1ab_0    conda-forge
itsdangerous              2.0.1              pyhd3eb1b0_0  
jasper                    2.0.33               h7c6fec8_1    conda-forge
jedi                      0.19.1             pyhd8ed1ab_0    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
joblib                    1.3.2              pyhd8ed1ab_0    conda-forge
jpeg                      9e                   hb7f2c08_3    conda-forge
jsonschema                4.17.3             pyhd8ed1ab_0    conda-forge
jupyter                   1.0.0             pyhd8ed1ab_10    conda-forge
jupyter_client            7.4.9              pyhd8ed1ab_0    conda-forge
jupyter_console           6.5.1              pyhd8ed1ab_0    conda-forge
jupyter_core              4.11.1           py37hf985489_0    conda-forge
jupyter_server            1.23.4             pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.3.0              pyhd8ed1ab_0    conda-forge
jupyterlab_widgets        3.0.9              pyhd8ed1ab_0    conda-forge
jxrlib                    1.1                  h35c211d_2    conda-forge
kiwisolver                1.4.4            py37h229a17a_0    conda-forge
krb5                      1.21.2               hb884880_0    conda-forge
lame                      3.100             hb7f2c08_1003    conda-forge
lcms2                     2.14                 h90f4b2a_0    conda-forge
lerc                      3.0                  he49afe7_0    conda-forge
libaec                    1.1.2                he965462_1    conda-forge
libblas                   3.9.0              20_osx64_mkl    conda-forge
libbrotlicommon           1.0.9                hb7f2c08_9    conda-forge
libbrotlidec              1.0.9                hb7f2c08_9    conda-forge
libbrotlienc              1.0.9                hb7f2c08_9    conda-forge
libcblas                  3.9.0              20_osx64_mkl    conda-forge
libcurl                   8.4.0                h726d00d_0    conda-forge
libcxx                    16.0.6               hd57cbcb_0    conda-forge
libdeflate                1.10                 h0d85af4_0    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 haf1e3a3_1    conda-forge
libexpat                  2.5.0                hf0c8a7f_1    conda-forge
libffi                    3.4.4                hecd8cb5_0  
libgfortran               5.0.0           13_2_0_h97931a8_1    conda-forge
libgfortran5              13.2.0               h2873a65_1    conda-forge
libglib                   2.78.1               h198397b_1    conda-forge
libiconv                  1.17                 hac89ed1_0    conda-forge
libidn2                   2.3.4                hb7f2c08_0    conda-forge
liblapack                 3.9.0              20_osx64_mkl    conda-forge
liblapacke                3.9.0              20_osx64_mkl    conda-forge
libllvm11                 11.1.0               h8fb7429_5    conda-forge
libnghttp2                1.58.0               h64cf6d3_0    conda-forge
libopencv                 4.6.0            py37h0e7fadd_5    conda-forge
libopus                   1.3.1                hc929b4f_1    conda-forge
libpng                    1.6.39               ha978bb4_0    conda-forge
libprotobuf               3.21.12              h7d26f99_2    conda-forge
libsodium                 1.0.18               hbcb3906_1    conda-forge
libssh2                   1.11.0               hd019ec5_0    conda-forge
libtasn1                  4.19.0               hb7f2c08_0    conda-forge
libtiff                   4.4.0                hfca7e8f_0    conda-forge
libunistring              0.9.10               h0d85af4_0    conda-forge
libvpx                    1.11.0               he49afe7_3    conda-forge
libwebp-base              1.3.2                h0dc2134_0    conda-forge
libxcb                    1.13              h0d85af4_1004    conda-forge
libxml2                   2.10.3               h201ad9d_4    conda-forge
libzlib                   1.2.13               h8a1eda9_5    conda-forge
libzopfli                 1.0.3                h046ec9c_0    conda-forge
llvm-openmp               17.0.6               hb6ac08f_0    conda-forge
llvmlite                  0.39.1           py37h5d31d3a_0    conda-forge
locket                    1.0.0              pyhd8ed1ab_0    conda-forge
lpips                     0.1.3              pyhd8ed1ab_0    conda-forge
lz4-c                     1.9.3                he49afe7_1    conda-forge
markupsafe                2.1.1            py37h69ee0a8_1    conda-forge
matplotlib                3.5.3            py37hf985489_2    conda-forge
matplotlib-base           3.5.3            py37h3748cd6_2    conda-forge
matplotlib-inline         0.1.6              pyhd8ed1ab_0    conda-forge
mistune                   3.0.2              pyhd8ed1ab_0    conda-forge
mkl                       2023.2.0         h54c2260_50500    conda-forge
mkl-devel                 2023.2.0         h694c41f_50500    conda-forge
mkl-include               2023.2.0         h6bab518_50500    conda-forge
moviepy                   1.0.3              pyhd8ed1ab_1    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
nbclassic                 1.0.0              pyhb4ecaf3_1    conda-forge
nbclient                  0.7.0              pyhd8ed1ab_0    conda-forge
nbconvert                 7.6.0              pyhd8ed1ab_0    conda-forge
nbconvert-core            7.6.0              pyhd8ed1ab_0    conda-forge
nbconvert-pandoc          7.6.0              pyhd8ed1ab_0    conda-forge
nbformat                  5.8.0              pyhd8ed1ab_0    conda-forge
ncurses                   6.4                  hcec6c5f_0  
nest-asyncio              1.5.8              pyhd8ed1ab_0    conda-forge
nettle                    3.9.1                h8e11ae5_0    conda-forge
networkx                  2.6.3              pyhd8ed1ab_1    conda-forge
notebook                  6.5.6              pyha770c72_0    conda-forge
notebook-shim             0.2.3              pyhd8ed1ab_0    conda-forge
numba                     0.56.3           py37h7da6166_0    conda-forge
numexpr                   2.8.3            py37h233bc55_0    conda-forge
numpy                     1.21.6           py37h345d48f_0    conda-forge
opencv                    4.6.0            py37hf985489_5    conda-forge
openh264                  2.3.1                hf0c8a7f_2    conda-forge
openjpeg                  2.5.0                h5d0d7b0_1    conda-forge
openssl                   3.2.0                hd75f5a5_1    conda-forge
ordered-set               4.1.0              pyhd8ed1ab_0    conda-forge
orjson                    3.8.1            py37h8052db5_0    conda-forge
p11-kit                   0.24.1               h65f8906_0    conda-forge
packaging                 23.2               pyhd8ed1ab_0    conda-forge
pandas                    1.3.5            py37h743cdd8_0  
pandoc                    3.1.3                h9d075a6_0    conda-forge
pandocfilters             1.5.0              pyhd8ed1ab_0    conda-forge
parso                     0.8.3              pyhd8ed1ab_0    conda-forge
partd                     1.4.1              pyhd8ed1ab_0    conda-forge
pcre2                     10.42                h0ad2156_0    conda-forge
pexpect                   4.8.0              pyh1a96a4e_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    9.2.0            py37ha6ba2b9_2    conda-forge
pip                       22.3.1           py37hecd8cb5_0  
pixman                    0.42.2               he965462_0    conda-forge
pkgutil-resolve-name      1.3.10             pyhd8ed1ab_1    conda-forge
proglog                   0.1.9                      py_0    conda-forge
prometheus_client         0.17.1             pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.41             pyha770c72_0    conda-forge
prompt_toolkit            3.0.41               hd8ed1ab_0    conda-forge
psutil                    5.9.3            py37h8052db5_0    conda-forge
pthread-stubs             0.4               hc929b4f_1001    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
py-opencv                 4.6.0            py37hc9f0f5e_5    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.17.2             pyhd8ed1ab_0    conda-forge
pynndescent               0.5.11             pyhca7485f_0    conda-forge
pyobjc-core               8.5.1            py37h11f76f7_0    conda-forge
pyobjc-framework-cocoa    8.5              py37h721a674_0    conda-forge
pyparsing                 3.1.1              pyhd8ed1ab_0    conda-forge
pyrsistent                0.18.1           py37h69ee0a8_1    conda-forge
pysocks                   1.7.1            py37hf985489_5    conda-forge
python                    3.7.12          hf3644f1_100_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-fastjsonschema     2.19.0             pyhd8ed1ab_0    conda-forge
python_abi                3.7                     4_cp37m    conda-forge
pytorch                   1.13.1                  py3.7_0    pytorch
pytz                      2023.3.post1       pyhd8ed1ab_0    conda-forge
pywavelets                1.3.0            py37h49e79e5_1    conda-forge
pyyaml                    6.0              py37h69ee0a8_4    conda-forge
pyzmq                     24.0.1           py37haa7bc41_0    conda-forge
qtconsole-base            5.4.4              pyha770c72_0    conda-forge
qtpy                      2.4.1              pyhd8ed1ab_0    conda-forge
readline                  8.2                  hca72f7f_0  
requests                  2.31.0             pyhd8ed1ab_0    conda-forge
rptree                    0.1.1                    pypi_0    pypi
rumpy                     1.0                       dev_0    <develop>
scikit-image              0.19.3           py37hbc43c61_1    conda-forge
scikit-learn              1.0.2            py37h572704e_0    conda-forge
scikit-video              1.1.11             pyh24bf2e0_0    conda-forge
scipy                     1.7.3            py37h4e3cf02_0    conda-forge
send2trash                1.8.2              pyhd1c38e8_0    conda-forge
setuptools                68.2.2             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.10               h225ccf5_0    conda-forge
sniffio                   1.3.0              pyhd8ed1ab_0    conda-forge
soupsieve                 2.3.2.post1        pyhd8ed1ab_0    conda-forge
sqlite                    3.41.2               h6c40b1e_0  
svt-av1                   1.4.1                hf0c8a7f_0    conda-forge
tbb                       2021.10.0            h1c7c39f_2    conda-forge
terminado                 0.17.1             pyhd1c38e8_0    conda-forge
threadpoolctl             3.1.0              pyh8a188c0_0    conda-forge
tifffile                  2021.11.2          pyhd8ed1ab_0    conda-forge
timm                      0.6.13             pyhd8ed1ab_0    conda-forge
tinycss2                  1.2.1              pyhd8ed1ab_0    conda-forge
tk                        8.6.12               h5d9f67b_0  
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
toolz                     0.12.0             pyhd8ed1ab_0    conda-forge
torchinfo                 1.8.0              pyhd8ed1ab_0    conda-forge
torchvision               0.14.1                 py37_cpu    pytorch
tornado                   6.2              py37h994c40b_0    conda-forge
tqdm                      4.66.1             pyhd8ed1ab_0    conda-forge
traitlets                 5.9.0              pyhd8ed1ab_0    conda-forge
typing-extensions         4.7.1                hd8ed1ab_0    conda-forge
typing_extensions         4.7.1              pyha770c72_0    conda-forge
umap-learn                0.5.3            py37hf985489_0    conda-forge
unicodedata2              14.0.0           py37h69ee0a8_1    conda-forge
urllib3                   2.1.0              pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.10             pyhd8ed1ab_0    conda-forge
webencodings              0.5.1              pyhd8ed1ab_2    conda-forge
websocket-client          1.6.1              pyhd8ed1ab_0    conda-forge
werkzeug                  2.2.2            py37hecd8cb5_0  
wheel                     0.38.4           py37hecd8cb5_0  
widgetsnbextension        4.0.9              pyhd8ed1ab_0    conda-forge
x264                      1!164.3095           h775f41a_2    conda-forge
x265                      3.5                  hbb4e6a2_3    conda-forge
xorg-libxau               1.0.11               h0dc2134_0    conda-forge
xorg-libxdmcp             1.1.3                h35c211d_0    conda-forge
xz                        5.4.2                h6c40b1e_0  
yaml                      0.2.5                h0d85af4_2    conda-forge
zeromq                    4.3.5                h93d8f39_0    conda-forge
zfp                       0.5.5                h4a89273_8    conda-forge
zipp                      3.15.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               h8a1eda9_5    conda-forge
zlib-ng                   2.0.7                hb7f2c08_0    conda-forge
zstd                      1.5.5                h829000d_0    conda-forge
(my_env) zl@iMac-Pro a_project % 

(my_env) zl@iMac-Pro a_project % pip list
Package                       Version      Editable project location
----------------------------- ------------ ------------------------------------
anyio                         3.7.1
appnope                       0.1.3
argon2-cffi                   23.1.0
argon2-cffi-bindings          21.2.0
attrs                         23.1.0
backcall                      0.2.0
backports.functools-lru-cache 1.6.5
beautifulsoup4                4.12.2
bleach                        6.1.0
Bottleneck                    1.3.5
Brotli                        1.0.9
cached-property               1.5.2
certifi                       2023.11.17
cffi                          1.15.1
charset-normalizer            3.3.2
click                         8.1.3
click-config-file             0.6.0
cloudpickle                   2.2.1
colorama                      0.4.6
comm                          0.1.4
configobj                     5.0.8
cycler                        0.11.0
cytoolz                       0.12.0
dask                          2022.2.0
debugpy                       1.6.3
decorator                     5.1.1
deepdiff                      6.7.1
defusedxml                    0.7.1
einops                        0.7.0
entrypoints                   0.4
exceptiongroup                1.2.0
fastjsonschema                2.19.0
filelock                      3.13.1
Flask                         2.2.2
fonttools                     4.38.0
fsspec                        2023.1.0
h5py                          3.7.0
huggingface-hub               0.16.4
idna                          3.6
imagecodecs                   2021.11.20
imageio                       2.31.5
imageio-ffmpeg                0.4.9
importlib-metadata            4.11.4
importlib-resources           6.0.0
ipykernel                     6.16.2
ipython                       7.33.0
ipython-genutils              0.2.0
ipywidgets                    8.1.1
itsdangerous                  2.0.1
jedi                          0.19.1
Jinja2                        3.1.2
joblib                        1.3.2
jsonschema                    4.17.3
jupyter                       1.0.0
jupyter_client                7.4.9
jupyter-console               6.5.1
jupyter_core                  4.11.1
jupyter-server                1.23.4
jupyterlab_pygments           0.3.0
jupyterlab-widgets            3.0.9
kiwisolver                    1.4.4
llvmlite                      0.39.1
locket                        1.0.0
lpips                         0.1.2
MarkupSafe                    2.1.1
matplotlib                    3.5.3
matplotlib-inline             0.1.6
mistune                       3.0.2
moviepy                       1.0.3
munkres                       1.1.4
nbclassic                     1.0.0
nbclient                      0.7.0
nbconvert                     7.6.0
nbformat                      5.8.0
nest-asyncio                  1.5.8
networkx                      2.6.3
notebook                      6.5.6
notebook_shim                 0.2.3
numba                         0.56.3
numexpr                       2.8.3
numpy                         1.21.6
opencv-python                 4.6.0
ordered-set                   4.1.0
orjson                        3.8.1
packaging                     23.2
pandas                        1.3.5
pandocfilters                 1.5.0
parso                         0.8.3
partd                         1.4.1
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        9.2.0
pip                           22.3.1
pkgutil_resolve_name          1.3.10
proglog                       0.1.9
prometheus-client             0.17.1
prompt-toolkit                3.0.41
psutil                        5.9.3
ptyprocess                    0.7.0
pycparser                     2.21
Pygments                      2.17.2
pynndescent                   0.5.11
pyobjc-core                   8.5.1
pyobjc-framework-Cocoa        8.5
pyparsing                     3.1.1
pyrsistent                    0.18.1
PySocks                       1.7.1
python-dateutil               2.8.2
pytz                          2023.3.post1
PyWavelets                    1.3.0
PyYAML                        6.0
pyzmq                         24.0.1
qtconsole                     5.4.4
QtPy                          2.4.1
requests                      2.31.0
rptree                        0.1.1
RUMpy                         1.0          /Users/zl/a_project/RUMpy
scikit-image                  0.19.3
scikit-learn                  1.0.2
scikit-video                  1.1.11
scipy                         1.7.3
Send2Trash                    1.8.2
setuptools                    68.2.2
six                           1.16.0
sniffio                       1.3.0
soupsieve                     2.3.2.post1
terminado                     0.17.1
threadpoolctl                 3.1.0
tifffile                      2021.11.2
timm                          0.6.13
tinycss2                      1.2.1
toml                          0.10.2
toolz                         0.12.0
torch                         1.13.1
torchinfo                     1.8.0
torchvision                   0.14.1
tornado                       6.2
tqdm                          4.66.1
traitlets                     5.9.0
typing_extensions             4.7.1
umap-learn                    0.5.3
unicodedata2                  14.0.0
urllib3                       2.1.0
wcwidth                       0.2.10
webencodings                  0.5.1
websocket-client              1.6.1
Werkzeug                      2.2.2
wheel                         0.38.4
widgetsnbextension            4.0.9
zipp                          3.15.0
(my_env) zl@iMac-Pro a_project %

**Comment by zoelee70** [comment]
(my_env) zl@iMac-Pro a_project % conda --version
conda 23.10.0
(my_env) zl@iMac-Pro a_project % pip --version
pip 22.3.1 from /Users/zl/miniconda3/envs/my_env/lib/python3.7/site-packages/pip (python 3.7)
(my_env) zl@iMac-Pro a_project %

**Comment by KeithGeorgeCiantar** [comment]
Ok I think I've figured it out now.

Please do:
`conda install einops=0.6.1`
`pip install prefetch_generator`

These should fix both the errors.

**Comment by zoelee70** [comment]
That worked!  Thank you for your help.  I will begin to try out some models in the morning.

**Comment by KeithGeorgeCiantar** [comment]
Great to hear! Good luck!
